### ISSUE TITLE
prometheus config

### ISSUE THREAD

**Issue by stefangweichinger** [ping7io/tls-grade-exporter#25]
Thanks for this exporter!

Trying to configure prometheus like:

```
  - job_name: 'tls-grade-exporter-1'
    scrape_interval: 10m
    metrics_path: "/probe?target=cloud.my.tld"
    static_configs:
      - targets: ['my-dockerhost:9155']
  
  - job_name: 'tls-grade-exporter-2'
    scrape_interval: 10m
    metrics_path: "/probe?target=www.my.tld"
    static_configs:
      - targets: ['my-dockerhost:9155']
      
```

Is that correct, or is there a more elegant way to check multiple URLs?
I'll increase "scrape_interval" to "1d" or so later, as soon as I see metrics in Grafana and came up with some basic dashboard.
